version: '3'
services:
  web:
    build: .
    command: rails server -b 0.0.0.0
    volumes:
      - ".:/json_schema_validation_builder"
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_PORT=5432
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
